### ISSUE TITLE
KMS security context not optional

### ISSUE THREAD

**Issue by redcatbear** [stevegal/jenkins-aws-bucket-credentials#4]
# Situation
When testing the plug-in with credentials encrypted with AWS KMS, the AWS client responds to the `decrypt()` request with the following error in case the field "KMS Encryption Context Key" is left empty:

```
com.amazonaws.services.kms.model.AWSKMSException: Invalid EncryptionContext
(Service: AWSKMS; Status Code: 400; Error Code: ValidationException;
Request ID: e*******4)
```

(Full stack trace see below).

## Expected Behaviour

KMS encryption context is ignored when configuration option  "KMS Encryption Context Key" is empty

## Actual Behaviour

KMS attempts context check.

## Steps to reproduce

1. Create ciphertext that is encrypted via KMS without explicitly using the encryption context
2. Upload resulting file as S3 object
3. Configure the plug-in without setting "KMS Encryption Context Key"
4. Try using the credential in a build (e.g. a pipeline build where you use it to pull the pipeline script from a Git repo)
5. Exception is thrown

## Environment

* Plug-in version: 0.2.2
* Jenkins version: 2.107.3
* Amazon Linux 4.9.62-21.56.amzn1.x86_64 #1 SMP Thu Nov 16 05:37:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~deb9u1-b11)

## Possible Causes

This is just a guess but looking at the code
```java
if (null != this.kmsSecretName &&
    null != this.kmsEncryptionContextKey) {
    LOGGER.info("decrypting with context");
    request.addEncryptionContextEntry(this.kmsEncryptionContextKey,
        this.kmsSecretName);
}
```
could it be that the field contents are empty `String`s instead of `null`?

### Full Stack Trace
```
 com.amazonaws.services.kms.model.AWSKMSException: Invalid EncryptionContext (Service: AWSKMS; Status Code: 400; Error Code: ValidationException; Request ID: e*******4)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1632)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.kms.AWSKMSClient.doInvoke(AWSKMSClient.java:3202)
	at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:3178)
	at com.amazonaws.services.kms.AWSKMSClient.executeDecrypt(AWSKMSClient.java:835)
	at com.amazonaws.services.kms.AWSKMSClient.decrypt(AWSKMSClient.java:810)
	at uk.co.stevegal.jenkins.plugins.awsbucketcredentials.AwsBucketCredentialsImpl.decryptString(AwsBucketCredentialsImpl.java:198)
	at uk.co.stevegal.jenkins.plugins.awsbucketcredentials.AwsBucketCredentialsImpl.getPassword(AwsBucketCredentialsImpl.java:157)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.createUnixStandardAskpass(CliGitAPIImpl.java:1813)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1680)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:405)
	at jenkins.plugins.git.GitSCMFileSystem$BuilderImpl.build(GitSCMFileSystem.java:351)
	at jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:196)
	at jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:172)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:108)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:298)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

**Comment by stevegal** [comment]
I’ll check and get back... sounds plausible. Did you see anything in the Jenkins log file (decrypting with context?)

**Comment by stevegal** [comment]
Should be fixed and released. I've done 2 releases, one which is backwardly compatible (0.2.3) if you need it, and it's included in the new 1.0.0 release.

Thanks for your time and suggestions. May I close?

**Comment by redcatbear** [comment]
Thanks for the fix @stevegal. Yes you can close the issue.

**Comment by stevegal** [comment]
Thanks. Sorry it took me so long to fix. I hope you find this plugin useful.
